import { z } from "zod";

export const propertySchema = z.object({
  title: z.string().optional().default(""),
  property_type: z.string().optional().default(""),
  city: z.string().optional().default(""),
  location: z.string().optional().default(""),
  street_number: z.string().optional().default(""),
  no_street_number: z.boolean().optional().default(false),
  block: z.string().optional().default(""),
  door: z.string().optional().default(""),
  urbanization_name: z.string().optional().default(""),
  price: z.coerce.number().optional().default(0),
  operation_sale: z.boolean().optional().default(true),
  operation_rent: z.boolean().optional().default(false),
  transaction_type: z.string().optional().default("Comprar"),
  condition: z.string().optional().default(""),
  construction_area: z.coerce.number().optional().default(0),
  private_area: z.coerce.number().optional().default(0),
  lot_area: z.coerce.number().optional().default(0),
  building_year: z.coerce.number().optional().default(0),
  heating_type: z.string().optional().default(""),
  energy_class: z.string().optional().default(""),
  orientation_north: z.boolean().optional().default(false),
  orientation_south: z.boolean().optional().default(false),
  orientation_east: z.boolean().optional().default(false),
  orientation_west: z.boolean().optional().default(false),
  built_in_wardrobes: z.boolean().optional().default(false),
  air_conditioning: z.boolean().optional().default(false),
  balcony_terrace: z.boolean().optional().default(false),
  parking: z.boolean().optional().default(false),
  storage: z.boolean().optional().default(false),
  pool: z.boolean().optional().default(false),
  garden: z.boolean().optional().default(false),
  elevator: z.boolean().optional().default(false),
  adapted_house: z.boolean().optional().default(false),
  luxury_house: z.boolean().optional().default(false),
  sea_view: z.boolean().optional().default(false),
  penthouse: z.boolean().optional().default(false),
  t0: z.boolean().optional().default(false),
  duplex: z.boolean().optional().default(false),
  is_top_floor: z.boolean().optional().default(false),
  floor: z.string().optional().default(""),
  total_floors: z.coerce.number().optional(),
  bathrooms: z.coerce.number().optional(),
  bedrooms: z.string().optional().default(""),
  internal_reference: z.string().optional().default(""),
  private_notes: z.string().optional().default(""),
  notes_visibility: z.string().optional().default(""),
  agent_captador: z.string().optional().default(""),
  agent_comercializador: z.string().optional().default(""),
  description: z.string().optional().default(""),
  video_url: z.string().optional().default(""),
  floor_plan_url: z.string().optional().default(""),
  virtual_tour_url: z.string().optional().default(""),
  status: z.string().optional().default("active"),
  featured: z.boolean().optional().default(false),
}).passthrough();

export type PropertyFormData = z.infer<typeof propertySchema>;
