import { z } from "zod";

export const propertySchema = z.object({
  title: z.string().min(1, "Título é obrigatório"),
  property_type: z.string().min(1, "Tipo de imóvel é obrigatório"),
  city: z.string().min(1, "Localidade é obrigatória"),
  location: z.string().min(1, "Nome da rua é obrigatório"),
  street_number: z.string().optional(),
  no_street_number: z.boolean().optional(),
  block: z.string().optional(),
  door: z.string().optional(),
  urbanization_name: z.string().optional(),
  operation_sale: z.boolean().optional(),
  operation_rent: z.boolean().optional(),
  price: z.number().min(0, "Preço deve ser maior que 0").optional(),
  transaction_type: z.string().default("Comprar"),
  condition: z.string().optional(),
  construction_area: z.number().optional(),
  private_area: z.number().optional(),
  lot_area: z.number().optional(),
  energy_class: z.string().optional(),
  heating_type: z.string().optional(),
  building_year: z.number().optional(),
  orientation_north: z.boolean().optional(),
  orientation_south: z.boolean().optional(),
  orientation_east: z.boolean().optional(),
  orientation_west: z.boolean().optional(),
  built_in_wardrobes: z.boolean().optional(),
  air_conditioning: z.boolean().optional(),
  terrace: z.boolean().optional(),
  balcony: z.boolean().optional(),
  parking: z.boolean().optional(),
  storage: z.boolean().optional(),
  pool: z.boolean().optional(),
  garden: z.boolean().optional(),
  elevator: z.boolean().optional(),
  balcony_terrace: z.boolean().optional(),
  adapted_house: z.boolean().optional(),
  luxury_house: z.boolean().optional(),
  sea_view: z.boolean().optional(),
  adapted_exterior: z.boolean().optional(),
  adapted_wheelchair: z.boolean().optional(),
  bank_property: z.boolean().optional(),
  internal_reference: z.string().optional(),
  private_notes: z.string().optional(),
  notes_visibility: z.string().optional(),
  agent_captador: z.string().optional(),
  agent_comercializador: z.string().optional(),
});

export type PropertyFormData = z.infer<typeof propertySchema>;
