// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmaqqgaxaogkhwhffqbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptYXFxZ2F4YW9na2h3aGZmcWJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMzQwNzAsImV4cCI6MjA2NDYxMDA3MH0.hjT5Jhj2QUrOZE2KdbgVJWz_uFgzc9yutr1pFg7H1is";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);